// <auto-generated />
using System;
using FacesmashAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacesmashAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015102321_UpdateSeedDataWithRealImages")]
    partial class UpdateSeedDataWithRealImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FacesmashAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("FacesmashAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.smith@student.uts.edu.au",
                            Gender = "F",
                            Name = "Alice",
                            PasswordHash = "123",
                            PhotoUrl = "https://randomuser.me/api/portraits/women/65.jpg",
                            Rating = 1200
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.jones@student.uts.edu.au",
                            Gender = "M",
                            Name = "Bob",
                            PasswordHash = "123",
                            PhotoUrl = "https://randomuser.me/api/portraits/men/52.jpg",
                            Rating = 1200
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie.brown@student.uts.edu.au",
                            Gender = "M",
                            Name = "Charlie",
                            PasswordHash = "123",
                            PhotoUrl = "https://randomuser.me/api/portraits/women/68.jpg",
                            Rating = 1200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
